import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <style jsx>
        {`
  h2{
    font-size: 38px;
  }

  h3{
    font-size: 28px;
  }
         `}
      </style>

      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>






      <main className={styles.main}>


        <h1 className={styles.title}>
          <span>Hunting Coder</span>
        </h1>

        <img className={styles.myImg} src='/homeimg.jpg' width={237} height={158} />
        <p className={styles.description}>A blog for hunting coders by a hunting coder.</p>


        <div>

          <h2>Latest Blogs: </h2>
          <div className="blogItem">
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>

          <div className="blogItem">
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>

          <div className="blogItem">
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>

          <div className="blogItem">
            <h1>How to learn Javascript in 2023?</h1>
            <p>Javascript is the language used to design logic for the web</p>
          </div>

          <div className="blogItem">
            <h1>How to learn Javascript in 2023?</h1>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>


      </main>
    </>
  )
}
